

## Spring Data source.
spring:  datasource:
    url: jdbc:mysql://localhost:3306/diccionario?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: m932006ac
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
    show-sql: true
  banner:
    location: classpath:banner.txt
    
#LOGGING
logging: 
  file:    path: C:/LOGS