#
#
## Data source.
#spring:#  datasource:#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: mysql://localhost:3306/diccionario
#    username: root
#    password: m932006ac
#  jpa:
#    show-sql: true
#  banner:
#    location: classpath:banner.txt



# Data source.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diccionario?serverTimezone=UTC
    username: root
    password: m932006ac
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  banner:
    location: classpath:banner.txt